apiVersion: apps/v1
kind: Deployment
metadata:
  name: galaxybackend
  labels:
    app: galaxy_backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: galaxy_backend
  template:
    metadata:
      labels:
        app: galaxy_backend
    spec:
      imagePullSecrets:
       - name: myghsecret
      containers:
       - name: customerdb
         image: ghcr.io/tvc-ctg/galaxy-bigfilms-backend-python:main
         ports:
         - containerPort: 8000
         env:
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
              secretKeyRef:
                name: mysqlsecret
                key: mysql-password
         - name: MYSQL_DATABASE
           valueFrom:
              secretKeyRef:
                name: mysqlsecret
                key: mysql-database
         - name: USER_NAME
           valueFrom:
              secretKeyRef:
                name: mysqlsecret
                key: mysql-user

         - name: IP_ADDRESS
           value: db
---
apiVersion: v1
kind: Service
metadata:
    name: galaxy-backend-service

spec:
    type: LoadBalancer
    ports:
      - protocol: "TCP"
        targetPort: 8000
        port: 8000
    selector:
         app: galaxy_backend
           
