apiVersion: apps/v1
kind: Deployment
metadata:
    name: dbdeploy
    labels:
        app: mydb
        type: front-end
spec:
    replicas: 1
    minReadySeconds: 30
    strategy:
        rollingUpdate:
          maxSurge: 0
        type: RollingUpdate
    selector:
        matchLabels:
            type: mydb
    template:
        metadata:
            name: myfirstpod
            labels:
                type: mydb
        spec:
            containers:
              - name: customerdb
                image: mysql:5.7
                env:
                  - name: MYSQL_ROOT_PASSWORD
                    valueFrom:
                        secretKeyRef:
                            name: mysqlsecret
                            key: mysql-password
                  - name: MYSQL_DATABASE
                    valueFrom:
                        secretKeyRef:
                            name: mysqlsecret
                            key: mysql-database
                ports:
                  - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
    name: db
spec:
    type: ClusterIP
    ports:
      - name: mysql
        targetPort: 3306
        port: 3306
    selector:
         type: mydb          
